In [49]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy

In [50]:
# generate 2k random lat and lngs and zip them
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs # checked

In [51]:
# adding lat and lngs into a list
coordinates = list(lat_lngs)
# create an list for random cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities) # found 748 cities from citipy

748

In [52]:
print(city)

saint-philippe

In [53]:
# perform api call 
import requests
from config import weather_api_key

#  url for opeanweathermap api Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Metric&APPID=" + weather_api_key

In [54]:
# loop over cities to retrieve data
city_data = []

print("beginning data retrieval")
print("--------------------------------")

no_info_city = []
for city in cities:
    # create an endpoint URL for each city.
    city_url = url + "&q=" + city.replace(" ", "+")
    
    
    try:
        # parse data in json
        city_info = requests.get(city_url).json()
        
        country = city_info['sys']['country']
        lng = city_info['coord']['lon']
        lat = city_info['coord']['lat']
        max_temp = city_info['main']['temp_max']
        humidity = city_info['main']['humidity']
        cloudiness = city_info['clouds']['all']
        wind_speed = city_info['wind']['speed']
        c_description = city_info['weather'][0]['description']
        
        city_data.append({"City":city.title(),
                          "Country": country,
                          "Lat":lat,
                          "Lng": lng,
                          "Max Temp": max_temp,
                          "Humidity": humidity,
                          "Cloudiness": cloudiness,
                          "Wind Speed": wind_speed,
                          "Current Description": c_description})
        
    except:
        print(f"{city} not found. Skiping")
        pass
print("--------------------------------")
print("Retrieval complete")
print("--------------------------------")

beginning data retrieval
--------------------------------
illoqqortoormiut not found. Skiping
barawe not found. Skiping
fevralsk not found. Skiping
alotau not found. Skiping
tsihombe not found. Skiping
taolanaro not found. Skiping
belushya guba not found. Skiping
barentsburg not found. Skiping
tungkang not found. Skiping
attawapiskat not found. Skiping
sentyabrskiy not found. Skiping
samusu not found. Skiping
khonuu not found. Skiping
uwayl not found. Skiping
vaitupu not found. Skiping
amderma not found. Skiping
dzhusaly not found. Skiping
bolungarvik not found. Skiping
nizhneyansk not found. Skiping
tabiauea not found. Skiping
qibili not found. Skiping
lar gerd not found. Skiping
mys shmidta not found. Skiping
karakose not found. Skiping
saleaula not found. Skiping
ust-kamchatsk not found. Skiping
karaul not found. Skiping
kadykchan not found. Skiping
marcona not found. Skiping
grand river south east not found. Skiping
quetzaltepec not found. Skiping
warqla not found. Skiping
tuggurt not found. Skiping
mocambique not found. Skiping
baboua not found. Skiping
umm durman not found. Skiping
gollere not found. Skiping
wulanhaote not found. Skiping
choucheng not found. Skiping
viligili not found. Skiping
lolua not found. Skiping
canitas not found. Skiping
rawannawi not found. Skiping
umzimvubu not found. Skiping
haibowan not found. Skiping
solsvik not found. Skiping
bargal not found. Skiping
abu jubayhah not found. Skiping
vitimskiy not found. Skiping
mutsamudu not found. Skiping
utiroa not found. Skiping
karakendzha not found. Skiping
aflu not found. Skiping
malwan not found. Skiping
ambodifototra not found. Skiping
louisbourg not found. Skiping
tlaxiaco not found. Skiping
pilao arcado not found. Skiping
paradwip not found. Skiping
shkotovo-22 not found. Skiping
dolbeau not found. Skiping
--------------------------------
Retrieval complete
--------------------------------

In [55]:
len(city_data) #  found 687 cities' weather info, out of 748 cities.

687

In [56]:
# add results into a new df
result_df = pd.DataFrame(city_data)
result_df.head()

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Albany,US,42.6001,-73.9662,17.79,82,92,1.95,overcast clouds
1,Hami,CN,42.8000,93.4500,8.39,26,3,3.34,clear sky
2,Landskrona,SE,55.8708,12.8302,10.01,68,70,5.68,broken clouds
3,Mahebourg,MU,-20.4081,57.7000,22.16,100,75,5.14,light rain
4,Ribeira Grande,PT,38.5167,-28.7000,21.42,90,100,10.47,overcast clouds

In [57]:
# formatting lat and lng columns
result_df["Lat"] = result_df["Lat"].map("{:.2f}".format)
result_df["Lng"] = result_df["Lng"].map("{:.2f}".format)
result_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Albany,US,42.60,-73.97,17.79,82,92,1.95,overcast clouds
1,Hami,CN,42.80,93.45,8.39,26,3,3.34,clear sky
2,Landskrona,SE,55.87,12.83,10.01,68,70,5.68,broken clouds
3,Mahebourg,MU,-20.41,57.70,22.16,100,75,5.14,light rain
4,Ribeira Grande,PT,38.52,-28.70,21.42,90,100,10.47,overcast clouds
5,Ushuaia,AR,-54.80,-68.30,9.81,40,40,5.66,light rain
6,Pustoshka,RU,56.34,29.37,3.16,88,62,2.34,broken clouds
7,Talnakh,RU,69.49,88.40,-5.09,97,94,2.50,light snow
8,Rikitea,PF,-23.12,-134.97,23.71,81,98,8.52,overcast clouds
9,Avarua,CK,-21.21,-159.78,25.03,73,100,4.63,overcast clouds

In [58]:
# export result_df to csv
output_csv = "WeatherPy_Database.csv"
result_df.to_csv(output_csv)

In [ ]:
# Deliverable 1 completed.